'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Item
    Public Property ItemID As Integer
    Public Property Name As String
    Public Property Price As Nullable(Of Decimal)

    Public Overridable Property OrderItems As ICollection(Of OrderItem) = New HashSet(Of OrderItem)

End Class
