'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderItem
    Public Property OrderItemID As Long
    Public Property OrderID As Nullable(Of Long)
    Public Property ItemID As Nullable(Of Integer)
    Public Property Quantity As Nullable(Of Integer)

    Public Overridable Property Item As Item
    Public Overridable Property Order As Order

End Class
