'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order
    Public Property OrderID As Long
    Public Property OrderNo As String
    Public Property CustomerID As Nullable(Of Integer)
    Public Property PMethod As String
    Public Property GTotal As Nullable(Of Decimal)

    Public Overridable Property Customer As Customer
    Public Overridable Property OrderItems As ICollection(Of OrderItem) = New HashSet(Of OrderItem)

End Class
